#server:
#  port: 8000
#
#spring:
#  application:
#    name: api-gateway
#  main:
#    web-application-type: reactive  # ✅ 반드시 reactive로 설정
#  config:
#    import: "config-service:http://localhost:8888"
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          default-filters:
#            - name: GlobalFilter
#              args:
#                baseMessage: Hello Global Filter
#                preLogger: true
#                postLogger: true
#          discovery:
#            locator:
#              enabled: true
#          globalcors:
#            cors-configurations:
#              '[/**]':
#                allowedOrigins: "http://localhost:3000"
#                allowedMethods: "*"
#                allowedHeaders: "*"
#                allowCredentials: true
#          routes:
#            - id: test-service
##              uri: http://localhost:8081
#              uri: lb://MY-TEST-SERVICE
#              predicates:
#                - Path=/test-service/**
#              filters:
##                - AddRequestHeader=f-request, test-request-header-by-yaml
##                - AddResponseHeader=f-response, test-response-header-from-yaml
#                - name: CustomFilter
#                - name: LoggingFilter
#                  args:
#                    baseMessage: Hello Filter
#                    preLogger: true
#                    postLogger: true
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/users/**
#              filters:
#                - JwtAuthorizationFilter
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
